app:
  host: '127.0.0.1'
  port: '8888'
  debug: true
  secret_key: 'e10adc3949ba59abbe56e057f20f883e'
db:
  host: '127.0.0.1'
  port: '3306'
  user: 'root'
  password: '123456'
  database: 'react-antd-admin'
